import { useEffect,useState } from "react";
import { useSearchParams } from "react-router-dom";
import API from "../../services/api";

export default function SkillGap(){
 const [params]=useSearchParams();const [employeeId,setEmployeeId]=useState(params.get("employee")||"");const [roleId,setRoleId]=useState(params.get("role")||"");const [roles,setRoles]=useState([]),[report,setReport]=useState(null),[recommendation,setRecommendation]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 useEffect(()=>{API.get("/roles").then(r=>setRoles(r.data.roles||[])).catch(e=>setError(e.response?.data?.message||"Could not load roles."))},[]);
 const generate=async e=>{e.preventDefault();if(!employeeId||!roleId)return setError("Enter an employee User ID and select a role.");setLoading(true);setError("");setReport(null);setRecommendation(null);try{const r=await API.get(`/skill-gap/${employeeId}/${roleId}`);setReport(r.data);try{const rec=await API.get(`/recommendations/${employeeId}/${roleId}`);setRecommendation(rec.data.recommendation)}catch(e){if(e.response?.status!==404)throw e}}catch(e){setError(e.response?.data?.message||"Skill-gap analysis failed.")}finally{setLoading(false)}};
 return <div className="container-page" style={{maxWidth:1000}}><div className="page-head"><h1>Skill Gap & Learning Recommendation</h1><p>Compare an employee's current skills with a role requirement.</p></div>{error&&<div className="alert alert-danger">{error}</div>}
 <div className="card"><form onSubmit={generate} className="form-grid"><div className="field"><label>Employee User ID</label><input required placeholder="MongoDB User _id" value={employeeId} onChange={e=>setEmployeeId(e.target.value)}/></div><div className="field"><label>Role requirement</label><select required value={roleId} onChange={e=>setRoleId(e.target.value)}><option value="">Select role</option>{roles.map(r=><option key={r._id} value={r._id}>{r.roleName} — {r.department||"General"}</option>)}</select></div><div className="field full"><button className="btn btn-primary" disabled={loading}>{loading?"Generating…":"Generate Skill Gap Report"}</button></div></form></div>
 {report&&<div className="grid grid-2" style={{marginTop:18}}><div className="card"><h2>{report.role?.roleName}</h2><div className="metric"><div className="label">Match percentage</div><div className="value">{report.matchPercentage}%</div></div><p><strong>{report.employee?.name}</strong> · {report.employee?.email}</p><h4>Matched</h4><div className="chips">{report.matchedSkills?.map(s=><span className="chip" key={s}>{s}</span>)}</div><h4 style={{marginTop:18}}>Missing</h4><div className="chips">{report.missingSkills?.map(s=><span className="chip" key={s}>{s}</span>)}</div><h4 style={{marginTop:18}}>Extra</h4><div className="chips">{report.extraSkills?.map(s=><span className="chip" key={s}>{s}</span>)}</div></div>
 <div className="card"><h2>AI Learning Recommendation</h2>{recommendation?<Recommendation data={recommendation}/>:report.aiRecommendation&&Object.keys(report.aiRecommendation).length?<Recommendation data={report.aiRecommendation}/>:<p style={{color:"var(--muted)"}}>No AI recommendation was returned. The skill-gap report itself is still available.</p>}</div></div>}
 </div>;
}
function Recommendation({data}){return <div>{Object.entries(data).map(([key,value])=><div key={key} style={{marginBottom:18}}><h4>{key.replace(/([A-Z])/g," $1")}</h4>{Array.isArray(value)?<div className="chips">{value.map((v,i)=><span className="chip" key={i}>{typeof v==="object"?JSON.stringify(v):String(v)}</span>)}</div>:typeof value==="object"&&value!==null?<pre style={{whiteSpace:"pre-wrap",background:"#fafbfe",padding:12,borderRadius:10,fontSize:12}}>{JSON.stringify(value,null,2)}</pre>:<p>{String(value)}</p>}</div>)}</div>}
